### ISSUE TITLE
Certificate on genesis.testnet.veres.one is expired.

### ISSUE THREAD

**Issue by peacekeeper** [veres-one/veres-one#16]
https://genesis.testnet.veres.one/

The certificate expired on 05/18/2018 06:09 PM.

**Comment by davidlehn** [comment]
Confirmed.  We're looking into it.

**Comment by davidlehn** [comment]
Testnet nodes should all be using valid certs now.  Certbot was renewing the letsencrypt certs but isn't reloading nginx to use them.  I'll open a new issue for that.  Thanks for the report.

**Comment by msporny** [comment]
## Post Mortem

The Veres One Testnet nodes are configured to use a combination of Nginx, Certbot, and Let's Encrypt to get their HTTPS certificates. The proper HTTPS certificates were fetched before they expired, but Certbot failed to  message Nginx to start serving the new certificates (Nginx caches the certificates in memory instead of re-reading them from disk when it detects an update). This caused the old certificates (in memory) to be served instead of using the new certificate (on disk).

We didn't see this issue because the graphical status monitor we use:

https://status.testnet.veres.one/

... relies on a 3rd party library that ignores certificate errors and therefore was showing that the entire network was up and running (which it was, but the certs for the HTTPS-based interface had failed).

In order to mitigate this issue in the future, we've done the following things:

* We now actively monitor for expired HTTPS certificates.
* We are using a non-graphical monitoring system (nagios) in addition to our graphical status monitor.
* We're exploring the proper way to ensure that certbot pushes nginx to reload the updated certificate from disk. We've done this manually for now. Testing this is in production is difficult as the certificates only expire once every 90 days. We'll keep an eye on things to make sure the auto-rotation happens correctly next time.

Thanks for the bug report @peacekeeper! We apologize for the inconvenience.
